### PR TITLE
Composer Split

### PR DESCRIPTION
**Pull request by malaretv**
Pushes composer out to it's own repo

### CODE REVIEW

**Comment by malaretv** [comment]
@ischneider/@mweisman ready for review

**Comment by ischneider** [comment]
Nice on adding the ant check for the composer.

The only thing I found was that I had to provide credentials for the composer repo as it was https. Was this needed for not-failing gracefully if someone doesn't have access?

Otherwise, `BUILD SUCCESSFUL` :smile:

**Comment by malaretv** [comment]
On testing without credentials `git sumodule update --init --recursive` seemed to handle it gracefully and just ignore private repos

**Comment by mweisman** [comment]
@malaretv do you mind using the ssh version of the url (git@github.com:boundlessgeo/composer.git)? This will auto-authenticate with an ssh key (if configured) rather than constantly prompting for a password.

Our build bots also have issues with being prompted for passwords.

**Comment by ischneider** [comment]
If we can't use the git URL (see question above re failing gracefully), seems we can use a token?

https://github.com/blog/1270-easier-builds-and-deployments-using-git-over-https-and-oauth

**Pull request merged**
