### PR TITLE
Added support for asynchronous import during indirect import

### PR DESCRIPTION
**Pull request by tbarsballe**
Import GET response now looks like:
```
      {
         "id": 0, 
         "preimport": [],
         "running": [],
         "imported": [
           {
             "task": 0, 
             "name": "stipple.shp",
             "type": "file"
             "layer": {
               "name": "stipple", 
               "workspace": "opengeo",
               ... rest of layer definition
             }
           }
         ], 
         "pending": [
           {
             "task": 1, 
             "name": "usa-merc.tif",
             "type": "file"
             "problem": "NO_CRS"
           }
         ],
         "ignored": [], 
         "failed": []
         "status":"complete"
         "tasksComplete":2
         "tasksTotal":2
         "importerEndpoint":"http://localhost:8080/geoserver/rest/importer/0"
       }
```      
The response is an object with 10 properties:
     * id - The identifier of this import job, needed to make modifications to it
     * status - The current status of the import. May be "pending", "running", or "complete"
     * tasksComplete - The number of tasks that have been processed and have either been successfully imported or given an error.
     * tasksTotal - The total number of tasks associated with this import
     * importerEndpoint - Endpoint to access the [GeoServer Importer REST api](http://docs.geoserver.org/stable/en/user/extensions/importer/rest_examples.html) for this import. 
     * preimport - Tasks that have been identified but not yet imported. Used by the database import and asynchronous import
     * running - Tasks that are currently running. Only used by asynchronous import
     * completed - Tasks that were successfully imported. Each task contains the resulting layer representation.
     * pending - Tasks that require further input from the user before being imported. The most common case being missing projection information. Each task contains a property named "problem" that identifies the issue.
     * ignored - Tasks that correspond to files that GeoServer doesn't recognize. Usually these are README files or other metadata files that don't correspond to data to be imported, but are present in the uploaded archive.
     * failed - Task that failed for some other reason. Each task contains an error trace that provides more information about the failure.

### CODE REVIEW

**Comment by tbarsballe** [comment]
Updated to have all imports asynchronous. If you try to update a currently running import, you will get an exception. This is to prevent running the same import concurrently, which could lead to data inconsistency. If you want to stop a currently running import, do an update with the attribute `"cancelled":true` in the request object.

**Comment by ischneider** [comment]
> Updated to have all imports asynchronous

There are a number of references to `boolean async` scattered throughout. If no longer used, these should be removed for clarity.

The use of `Thread.sleep(100)` is a test failure waiting to happen. A better approach would be to poll the import task periodically.

The importer REST API also provides a progress endpoint to get the actual progress (number of features) and status of the import. Returning this URL to the client would enable eventual use of this information. See `org.geoserver.importer.rest.TaskResource`

**Comment by tbarsballe** [comment]
The Importer rest api endpoint is just `/geoserver/rest/imports/<id>`. Since we already return the id, and a user would need to have some knowledge about the Importer API to use it effectively, I feel like this should be sufficient. This also keeps the two APIs independant but still compatible. 
Also, as far as I can tell from the (rather sparse) documentation on the Importer rest API, the progress is just tracked by the statuses of the tasks (Complete, pending, etc.). This Composer Import API gives a more detailed/easier to calculate indication of progress, by boxing tasks by status, and listing the total number of tasks/number of tasks completed.

Updates pending for your other two points.

**Comment by ischneider** [comment]
> The Importer rest api endpoint is just /geoserver/rest/imports/<id>. Since we already return the id, and a user would need to have some knowledge about the Importer API to use it effectively, I feel like this should be sufficient. This also keeps the two APIs independant but still compatible.

The point of a REST API is to tell the client where to access resources, not require hard-coded client knowledge of how to use it.

> Also, as far as I can tell from the (rather sparse) documentation on the Importer rest API, the progress is just tracked by the statuses of the tasks (Complete, pending, etc.). 

As noted earlier, it actually gives fine-grained progress of the number of features ingested and the total, allowing for a progress bar. For larger datasets, this feedback is much nicer than a spinning wheel.

> This Composer Import API gives a more detailed/easier to calculate indication of progress, by boxing tasks by status, and listing the total number of tasks/number of tasks completed.

This is not as detailed as the number of features processed within a given task.

**Comment by tbarsballe** [comment]
I was not aware you could actually get progress on a per-feature basis from the Importer API - this is not well documented. Given that, it makes sense to add the endpoint.

**Comment by ischneider** [comment]
> this is not well documented

secret sauce

**Comment by tbarsballe** [comment]
Updated with changes. It may be safer to wait and merge this until after the frontend work is also done, because this change will likely break Composer as it stands right now (due to the requirement to poll the api for results).

**Comment by tbarsballe** [comment]
@eshon I have updated this to be up-to-date with master.
The ImportContext is now created asyncronously, which means that you will need to poll the import using GET before you see the list of import tasks.
Added a `"task"` attribute to the response, which describes the currenty running task.
Also note: Because creating the import context is now async, you will have to choose what to import from a file, similar to how importing a databae works. Best bet is probably to just import everything when importing a file (ie. hide this functionality from the user)

**Comment by tbarsballe** [comment]
@ischneider I have added support here for using createContextAsync()
This required some rather significant changes in order to maintain a consistent id (Since the id returned from createContextAsync is distinct from the ImportContext id). A review of this new stuff would be appreciated.

**Comment by tbarsballe** [comment]
Composer UI work completed and tested. Merging.

**Pull request merged**
