### PR TITLE
Updated composer keyboard shortcuts

### PR DESCRIPTION
**Pull request by tbarsballe**
Updated the documentation on keyboard shortcuts to match changes in composer. Also added previously missin sections on Select and indent shortcuts to match updated keys_list.png image.

@bmmpxf do you want to do a quick review of this? Also, do you know if the changed shortcuts are ever referenced elsewhere in the composer documentation?

### CODE REVIEW

**Comment by bartvde** [comment]
just a note that the Cmd key is not working with Composer keyboard shortcuts on OSX for me, only with Ctrl

**Comment by tbarsballe** [comment]
As of how recently? The change just got pushed to the composer repo on Friday, so I am not sure that horizon is updated yet.

**Comment by bartvde** [comment]
I tested with the 4.6 release.
Cmd key doesn't work on OSX Ctrl does.

**Comment by tbarsballe** [comment]
Yes, that issue has just been fixed, so it won't be in the 4.6 release. Should be in 4.7 though.

**Comment by bartvde** [comment]
ah great news! Thanks for fixing.

**Pull request merged**
