### PR TITLE
Tab Title

### PR DESCRIPTION
**Pull request by RobertDenis**
Adding more descriptive information to the tab title.

### CODE REVIEW

**Comment by eshon** [comment]
Some lines are too long to display in most browser tabs.

**Comment by RobertDenis** [comment]
Is it an issue that the lines are too long? They'll display on mouseover, but I can shorten them if you'd like, just let me know what you'd like them to say.

**Comment by eshon** [comment]
Shorten 'All Project Workspaces' to 'All Workspaces'

Remove the prefixes 'Workspace:' and 'Editing Map:'

**Comment by tbarsballe** [comment]
Ported to composer repo

**Pull request closed without merging**
