### PR TITLE
Lonlat mousepos

### PR DESCRIPTION
**Pull request by eshon**
SUITE-382  Adding lon lat cursor to Composer and Map view as well as option to turn off map controls from Display dropdown in the Toolbar.

### CODE REVIEW

**Comment by ischneider** [comment]
Can the element toggling be done w/ more specific selectors (i.e. `#map .bounds`) to prevent accidental mysterious disappearances? Can `#map .ol-control` be used for the `all` toggle?

Along those lines, since the toggling is directly related to a selector, could the `mapcontrols` scope hash contain the selectors instead of the indirection in the olMap directive?

What if we want to persist the choice? Either globally or per map?

Thanks for not using jquery :smile: 

Unrelated:

`display.js` has a large template embedded? Time to extract?
When can we use ng-annotate :smile: ?

**Comment by eshon** [comment]
screen shot 2015-03-09 at 4 12 21 pm

They don't all have ol-control - custom controls don't get ol-control css automatically.
Considered using the ol-overlaycontainer-stopevent div but that's hacky because its not clear from any ol3 documentation that that would be the container for all map controls not in an external div.

A harder core dev would put all the controls in a special div as well as give users the option to specify the precision of their lonlats.  A harder core designer might lay out the controls more nicely.  

Sure, we could put it in some directive variables so that the olMap directive could pass it to its own controls to show or hide themselves.  There are probably 20 other event triggers we could do that for actually.

**Comment by ischneider** [comment]
> They don't all have ol-control - custom controls don't get ol-control css automatically.

Can they be added manually? Obviously not critical...

> Sure, we could put it in some directive variables so that the olMap directive could pass it to its own controls to show or hide themselves.

I struggle w/ the better approach - passing things around via directive or through a shared service. Seems like for reusable components the former is the correct approach. The latter is less trouble but more wired up.

>  There are probably 20 other event triggers we could do that for actually. When I see someone implement that pattern i'll be sure to copy it in the future.

I've noticed. I've seen various 'best practices' described related to events and using the rootScope event bus pattern. One concern is leaking references when controllers are created and destroyed. Another is a fragile API.

For at least some of the things I saw, it looks the pattern would be to use a service and rely on data-binding instead of events.

> As for persisting choices...the scope (user? session?) and implementation of that is for you devs to figure out.

Touché - implementation perhaps but was more wondering aloud (and in the wrong place) about the concept. And good question - where do they persist?

**Comment by eshon** [comment]
Doing this with ol-control doesn't work because the UI allows users to toggle everything individually as well, so toggle-all on/off will not work correctly if one control is out of sync with the rest.  But did add ol-control to all controller divs for the future.

Doing with in the parent scope via a directive option is weird too because scope.watch in the child scope isn't really what I want - with a toggle the watched variable signalled by the event e.g. 'all' may not change if triggered twice in a row.  vmalaret suggested using a css parent class but that'd require a lot of css child classes to cover all the options of controls to toggle.  I added an arbitrary variable onto the watch variable with each toggle to trigger the scope.watch variable change, but it's hacky.

Appreciate the goal of separating App.Event triggers from the ol-map directive now tho, after vmalaret explained it.  New PR will be in composer repo.

**Comment by eshon** [comment]
Added as PR in new Composer Repo.

**Pull request closed without merging**
