### PR TITLE
Removing enterprise / basic documentation split

### PR DESCRIPTION
**Pull request by bmmpxf**

### CODE REVIEW

**Comment by bmmpxf** [comment]
@mweisman When you get a chance, can you please take a look at the build file changes in this PR and give it the :+1:?

**Comment by mweisman** [comment]
@bmmpxf I'm getting a build failure:
```
sphinx:
     [echo] sphinx-build -A suite_version=4.6-SNAPSHOT  -q -j 4 -W -b latex -d /var/lib/jenkins/jobs/suite-docs/workspace/docs/usermanual/target/doctrees . /var/lib/jenkins/jobs/suite-docs/workspace/docs/usermanual/target/latex
     [exec] 
     [exec] Warning, treated as error:
     [exec] /var/lib/jenkins/jobs/suite-docs/workspace/docs/usermanual/source/intro/installation/windows/qgis.rst:: WARNING: unusable reference target found: ../../qgis/
     [exec] 
     [exec] Result: 1
     [exec] make: *** No rule to make target `all-pdf'.  Stop.
```
https://r2d2.boundlessgeo.com/jenkins/job/suite-docs/459/console

**Comment by jodygarnett** [comment]
I added -W to the flags for user manual to catch errors like the one mentioned.

**Comment by mweisman** [comment]
@jodygarnett No go. Same issue.

https://r2d2.boundlessgeo.com/jenkins/job/suite-docs/460/console

**Comment by jodygarnett** [comment]
Mike has it working here, I think it is a while since we built PDF.

Does the global build call "build" or "build-html" ?

**Comment by bmmpxf** [comment]
Try now?

**Comment by mweisman** [comment]
Ok. Build looks ok but there's an issue with the assembly.
 Looks like something is still passing a path with `basic` in it to https://github.com/boundlessgeo/suite/blob/docmerge/docs/build.xml#L29

https://r2d2.boundlessgeo.com/jenkins/job/suite-docs/463/console

**Comment by jodygarnett** [comment]
Are you going to look at that? I was trying to stay away from the build side of the merge.

**Comment by mweisman** [comment]
Have to run for the day but I'll take a look first time tomorrow morning.

**Pull request merged**
